# create your drupal and postgres config here, based off the last assignment
# careful with spaces, indent and uppercase
#its working
version: '2'
services:
  drupal:
    image: drupal
    ports:
      - "1337:80"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
